# Generated by Django 5.1.2 on 2025-11-20 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
